# Generated by Django 4.1.4 on 2022-12-30 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='electronico_categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='electronicomodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=300)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('marca', models.CharField(blank=True, max_length=30)),
                ('avatar', models.FileField(blank=True, upload_to='electronico')),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='ímagen')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='ímagen')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='ímagen')),
                ('imagen4', models.ImageField(blank=True, null=True, upload_to='ímagen')),
                ('procesador', models.CharField(blank=True, max_length=50)),
                ('precio', models.CharField(blank=True, max_length=15)),
                ('in_portada', models.BooleanField(default=False)),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('tamaño', models.CharField(blank=True, max_length=5)),
                ('detalles', models.TextField(blank=True)),
                ('almacenamiento', models.CharField(blank=True, choices=[('32', '32'), ('64', '64'), ('128', '128'), ('256', '256')], max_length=3)),
                ('rating', models.PositiveIntegerField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('categiria_electronico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.electronico_categoria')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='inicio.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='tablesmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('marca', models.CharField(max_length=30)),
                ('avatar', models.FileField(upload_to='tables')),
                ('detalle', models.TextField()),
                ('almacenamiento', models.CharField(max_length=30)),
                ('precio', models.CharField(max_length=10)),
                ('tipo', models.ManyToManyField(blank=True, related_name='table', to='inicio.electronicomodel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='monitoresmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('avatar', models.FileField(upload_to='tables')),
                ('precio', models.CharField(max_length=10)),
                ('detalle', models.TextField()),
                ('tamaño', models.CharField(max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stok', models.PositiveIntegerField()),
                ('tipo', models.ManyToManyField(blank=True, related_name='monitores', to='inicio.electronicomodel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='laptopmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=50)),
                ('procesador', models.CharField(max_length=50)),
                ('avatar', models.FileField(upload_to='laptop')),
                ('precio', models.CharField(max_length=10)),
                ('almacenamiento', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stok', models.PositiveIntegerField()),
                ('tipo', models.ManyToManyField(blank=True, related_name='laptop', to='inicio.electronicomodel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cpumodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('procesador', models.CharField(max_length=50)),
                ('avatar', models.FileField(upload_to='tables')),
                ('precio', models.CharField(max_length=10)),
                ('detalle', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stok', models.PositiveIntegerField()),
                ('tipo', models.ManyToManyField(blank=True, related_name='cpu', to='inicio.electronicomodel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='celularesmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('modelo', models.CharField(max_length=50)),
                ('avatar', models.FileField(upload_to='celulares')),
                ('precio', models.CharField(max_length=5)),
                ('detalles', models.TextField()),
                ('almacenamiento', models.CharField(choices=[('32', '32'), ('64', '64'), ('128', '128'), ('256', '256')], max_length=3)),
                ('color', models.CharField(choices=[('R', 'ROJO'), ('N', 'NEGRO'), ('B', 'BLANCO'), ('O', 'OTROS')], max_length=10)),
                ('rating', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stok', models.PositiveIntegerField()),
                ('tipo', models.ManyToManyField(blank=True, related_name='celular', to='inicio.electronicomodel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='acesoriomodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('tipos', models.CharField(max_length=50)),
                ('detalle', models.TextField()),
                ('avatar', models.FileField(upload_to='acesorios')),
                ('precio', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stok', models.PositiveIntegerField()),
                ('tipo', models.ManyToManyField(blank=True, related_name='acesorio', to='inicio.electronicomodel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
