# Generated by Django 4.1.4 on 2022-12-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acesoriomodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('tipo', models.CharField(max_length=50)),
                ('detalle', models.TextField()),
                ('avatar', models.FileField(upload_to='acesorios')),
                ('precio', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stok', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='celularesmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('modelo', models.CharField(max_length=50)),
                ('avatar', models.FileField(upload_to='celulares')),
                ('precio', models.CharField(max_length=5)),
                ('detalles', models.TextField()),
                ('almacenamiento', models.CharField(choices=[('32', '32'), ('64', '64'), ('128', '128'), ('256', '256')], max_length=3)),
                ('color', models.CharField(choices=[('R', 'ROJO'), ('N', 'NEGRO'), ('B', 'BLANCO'), ('O', 'OTROS')], max_length=10)),
                ('rating', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stok', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cpumodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('procesador', models.CharField(max_length=50)),
                ('avatar', models.FileField(upload_to='tables')),
                ('precio', models.CharField(max_length=10)),
                ('detalle', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stok', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='laptopmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=50)),
                ('procesador', models.CharField(max_length=50)),
                ('avatar', models.FileField(upload_to='laptop')),
                ('precio', models.CharField(max_length=10)),
                ('almacenamiento', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stok', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='monitoresmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('avatar', models.FileField(upload_to='tables')),
                ('precio', models.CharField(max_length=10)),
                ('detalle', models.TextField()),
                ('tamaño', models.CharField(max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stok', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tablesmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('marca', models.CharField(max_length=30)),
                ('avatar', models.FileField(upload_to='tables')),
                ('detalle', models.TextField()),
                ('almacenamiento', models.CharField(max_length=30)),
                ('precio', models.CharField(max_length=10)),
            ],
        ),
    ]
