# Generated by Django 4.1.4 on 2022-12-30 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronicomodel',
            name='categiria_electronico',
        ),
    ]
