# Generated by Django 4.1.4 on 2022-12-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicomodel',
            name='precio',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
