# Generated by Django 4.1.4 on 2022-12-30 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_remove_electronicomodel_categiria_electronico'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicomodel',
            name='categoria_elect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inicio.electronico_categoria'),
            preserve_default=False,
        ),
    ]
