# Generated by Django 4.1.4 on 2022-12-30 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_electronicomodel_categoria_elect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronicomodel',
            name='categoria_elect',
        ),
        migrations.DeleteModel(
            name='electronico_categoria',
        ),
    ]
