# Generated by Django 4.1.4 on 2022-12-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_alter_electronicomodel_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicomodel',
            name='in_portada',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
