# Generated by Django 4.1.4 on 2023-01-02 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_vistas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vistas',
            old_name='hora',
            new_name='created',
        ),
    ]
