# Generated by Django 4.1.4 on 2022-12-28 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_alter_electronicomodel_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicomodel',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='inicio.categoria'),
        ),
    ]
