# Generated by Django 4.1.4 on 2022-12-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_alter_electronicomodel_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicomodel',
            name='in_portada',
            field=models.BooleanField(default=False),
        ),
    ]
