# Generated by Django 4.1.4 on 2023-01-02 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_rename_hora_vistas_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistas',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electronico', to='inicio.electronicomodel'),
        ),
    ]
