# Generated by Django 4.1.4 on 2022-12-29 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='card_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=300)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('marca', models.CharField(blank=True, max_length=30)),
                ('avatar', models.FileField(blank=True, upload_to='electronico')),
                ('procesador', models.CharField(blank=True, max_length=50)),
                ('precio', models.CharField(blank=True, max_length=15)),
                ('in_portada', models.BooleanField(default=False)),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('tamaño', models.CharField(blank=True, max_length=5)),
                ('detalles', models.TextField(blank=True)),
                ('almacenamiento', models.CharField(blank=True, choices=[('32', '32'), ('64', '64'), ('128', '128'), ('256', '256')], max_length=3)),
                ('rating', models.PositiveIntegerField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
